title: qs.zhao's blog
logo: /assets/img/zqs_photo.png
description: I used to be graduate student in Chinese Academy of Sciences, Now I am a Ph.D. candidate in Tongji University. I am doing some work in Machine Learning and Computer Vision. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
