title: qs.zhao's blog
logo: /assets/img/gray2.jpg
description: Dr. Qingsong Zhao (赵青松) is a Frontier Interdisciplinary Researcher at TeleAI, Institute of Artificial Intelligence, China Telecom, which is led by Prof. Xuelong Li, the CTO and Chief Scientist of China Telecom.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

