title: qs.zhao's blog
logo: /assets/img/zqs_photo.png
description: I am a graduate student studying at Shenzhen Advanced Technology Research Institute, Chinese Academy of Sciences.Now I am doing some work in computer vision.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
